#!/usr/bin/env node
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const args = process.argv.slice(2);
const inputArg = args.find(a => a.startsWith('--input='));
const batchArg = args.find(a => a.startsWith('--batch='));
const outputDir = resolve('src/data/remedyBatches');

if (!inputArg || !batchArg) {
  console.error('Usage: node generate-batch.mjs --input=reports/batch-01-discovery.json --batch=2');
  process.exit(1);
}

const inputFile = inputArg.slice(8);
const batchNum = batchArg.slice(7).replace(/[^0-9]/g, '');
const output = resolve(outputDir, `remedyBatch${batchNum}.js`);

mkdirSync(outputDir, { recursive: true });

const discovery = JSON.parse(readFileSync(resolve(inputFile), 'utf8'));

function evidenceType(raw) {
  if (!raw || raw.length === 0) return 'journal-article';
  const joined = raw.join(' ').toLowerCase();
  if (joined.includes('meta-analysis')) return 'meta-analysis';
  if (joined.includes('systematic review')) return 'systematic-review';
  if (joined.includes('randomized controlled trial')) return 'randomized-trial';
  if (joined.includes('clinical trial')) return 'clinical-trial';
  if (joined.includes('practice guideline')) return 'clinical-guideline';
  return 'journal-article';
}

function databaseFor(candidate) {
  if (candidate.retrievalSource === 'PubMed') return 'PubMed';
  if (candidate.retrievalSource === 'Europe PMC') return 'Europe PMC';
  if (candidate.retrievalSource?.includes('Google Scholar')) return 'Google Scholar';
  return candidate.retrievalSource || 'PubMed';
}

function findingFromAbstract(abstract, title) {
  let text = (abstract || '').replace(/&#xa0;/g, ' ').replace(/&nbsp;/g, ' ').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
  if (!text) return `Study on ${title || 'this intervention'} — full text review recommended.`;
  const sentences = text.split(/\.\s+/).filter(s => s.length > 30);
  if (sentences.length === 0) return `Study on ${title || 'this intervention'} — abstract too short for extraction.`;
  const conclusionish = sentences.find(s => /conclud|suggest|found|demonstrat|indicat|result|may|effect|improv|reduc/i.test(s));
  const finding = conclusionish || sentences.slice(0, 2).join('. ');
  return (finding.endsWith('.') ? finding : finding + '.').substring(0, 250);
}

const candidates = [];
const existingPmids = new Set();
for (let b = 1; b < Number(batchNum); b++) {
  const batchFile = resolve(outputDir, `remedyBatch${b}.js`);
  if (existsSync(batchFile)) {
    const content = readFileSync(batchFile, 'utf8');
    for (const m of content.matchAll(/pmid:\s*'(\d+)'/g)) existingPmids.add(m[1]);
    for (const m of content.matchAll(/doi:\s*'([^']+)'/g)) existingPmids.add(m[1]);
  }
}
for (const packet of discovery.packets || []) {
  const symptomCode = packet.symptomCode;
  for (const candidate of packet.candidates || []) {
    if (!candidate.url) continue;
    const key = candidate.pmid || candidate.doi;
    if (key && existingPmids.has(key)) continue;
    candidates.push({ ...candidate, symptomCode });
  }
}

const deduped = [];
const seenPmids = new Set();
const seenSymptomIntervention = new Set();
for (const c of candidates) {
  const key = c.pmid || c.doi || c.url;
  if (seenPmids.has(key)) continue;
  seenPmids.add(key);
  const pairKey = `${c.symptomCode}__${c.intervention || c.title}`;
  if (seenSymptomIntervention.has(pairKey)) continue;
  seenSymptomIntervention.add(pairKey);
  deduped.push(c);
}

const functionId = `REMEDY_BATCH_${batchNum}`;
const exportId = `applyRemedyBatch${batchNum}`;

const lines = [];
lines.push(`// Auto-generated by scripts/generate-batch.mjs — do not edit manually.`);
lines.push(`// Each remedy uses a specific verified citation (PMID or DOI).`);
lines.push(``);
lines.push(`export function ${exportId}(remedies = []) {`);
lines.push(`  const map = new Map(remedies.map(r => [r.id, r]));`);
lines.push(``);

for (const [i, candidate] of deduped.entries()) {
  const id = `rem_gen${batchNum}_${String(i + 1).padStart(2, '0')}`;
  const intervention = candidate.intervention || 'remedy';
  const symptomCode = candidate.symptomCode;
  const symptomLabel = symptomCode.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
  const name = (candidate.tagline || `${intervention.replace(/\b\w/g, c => c.toUpperCase())} for ${symptomLabel}`).replace(/[\r\n]+/g, ' ').replace(/'/g, "\\'").substring(0, 100);
  const pmid = candidate.pmid || '';
  const doi = candidate.doi || '';
  const url = candidate.url || '';
  const journal = (candidate.journal || 'Journal').replace(/[\r\n]+/g, ' ').replace(/'/g, "\\'").substring(0, 100);
  const pubTypes = candidate.publicationTypes || [];
  const database = databaseFor(candidate);
  const evType = evidenceType(pubTypes);
  const finding = findingFromAbstract(candidate.abstract, candidate.title).replace(/[\r\n]+/g, ' ').replace(/'/g, "\\'").substring(0, 200);
  const category = candidate.category || 'Supplement';

  lines.push(`  map.set('${id}', {`);
  lines.push(`    id: '${id}',`);
  lines.push(`    name: '${name}',`);
  lines.push(`    category: '${category}',`);
  lines.push(`    symptoms: ['${symptomCode}'],`);
  lines.push(`    primarySymptoms: ['${symptomCode}'],`);
  lines.push(`    secondarySymptoms: [],`);
  lines.push(`    shortDescription: '${finding}',`);
  lines.push(`    longDescription: 'This remedy entry is backed by a verified clinical or review paper. Consult the source for full context.' ,`);
  lines.push(`    howToUse: 'Follow professional guidance for this remedy type.' ,`);
  lines.push(`    warnings: ['Consult a healthcare professional before use.'],`);
  lines.push(`    contraindications: [],`);
  lines.push(`    isPurchasable: ${category === 'OTC' || category === 'Supplement'},`);
  lines.push(`    childSafe: false,`);
  lines.push(`    childSafetyNote: 'Do not use in children without professional guidance.' ,`);
  lines.push(`    difficulty: 'Moderate',`);
  lines.push(`    cost: '$',`);
  lines.push(`    ingredients: [],`);
  lines.push(`    allergen_tags: [],`);
  lines.push(`    isFeatured: false,`);
  lines.push(`    rating: 0,`);
  lines.push(`    reviewCount: 0,`);
  lines.push(`    researchPapers: [{`);
  const title = (candidate.title || name).replace(/[\r\n]+/g, ' ').replace(/'/g, "\\'").substring(0, 150);
  lines.push(`      title: '${title}',`);
  lines.push(`      journal: '${journal}',`);
  lines.push(`      url: '${url}',`);
  lines.push(`      sourceDatabase: '${database}',`);
  lines.push(`      evidenceType: '${evType}',`);
  lines.push(`      keyFinding: '${finding.substring(0, 250)}',`);
  if (pmid) lines.push(`      pmid: '${pmid}',`);
  if (doi) lines.push(`      doi: '${doi}',`);
  lines.push(`    }],`);
  lines.push(`  });`);
  lines.push(``);
}

lines.push(`  const existing = new Set(remedies.map(r => r.id));`);
lines.push(`  const newRemedies = [...map.values()].filter(r => !existing.has(r.id));`);
lines.push(`  return [...remedies, ...newRemedies];`);
lines.push(`}`);

mkdirSync(dirname(output), { recursive: true });
writeFileSync(output, lines.join('\n'));

console.log(`Generated ${deduped.length} remedies in ${output}`);
console.log(`Symptoms covered: ${[...new Set(deduped.map(c => c.symptomCode.replace(/_/g, ' ')))].join(', ')}`);
console.log(`Source distribution: ${JSON.stringify(deduped.reduce((acc, c) => { acc[databaseFor(c)] = (acc[databaseFor(c)] || 0) + 1; return acc; }, {}))}`);
console.log(`Category distribution: ${JSON.stringify(deduped.reduce((acc, c) => { acc[c.category || 'unknown'] = (acc[c.category || 'unknown'] || 0) + 1; return acc; }, {}))}`);
console.log(`\nTo wire into the runtime catalog, add to src/data/evidence-candidate-discovery.mjs or src/store/catalogStore.js.`);
